### ISSUE TITLE
SSH broken pipi error; automatic logout

### ISSUE THREAD

**Issue by AlexDo1** [CAMELS-DE/docs#2]
After just a few minutes my SSH connection to the server disconnects with the following error: `client_loop: send disconnect: Broken pipe`.

Although this could potentially be fixed on the client side, I think we should make changes on the server side SSH configuration.  
There are two important parameters in the file `/etc/ssh/sshd_config`:
- `ClientAliveInterval` -> currently set to `120`
- `ClientAliveCountMax` -> currently set to `2`
This means that after 120 seconds, the server checks if the client is alive and again after 240 seconds (2 retries).  
I think we can increase the values in `/etc/ssh/sshd_config` at least to `300` and `3`, which gives us 15 minutes time before disconnection.  

The `camel` user has no permissions to do that, so you would have to take care of that @mmaelicke.

From:
https://linuxhandbook.com/ssh-broken-pipe-error/#:~:text=Host%20*%0AServerAliveInterval%20600-,Method%202%3A%20Server%20side%20SSH%20config%20change,-The%20SSH%20config

**Comment by mmaelicke** [comment]
I added these settings already, can you check if that did the trick? (formaly there was 0 and 1)

**Comment by AlexDo1** [comment]
Yes, the new values are way better.
I tried to test after which time I disconnect now, I would think after 4 minutes.  
But somehow I did not disconnect, even after 6 minutes, but I also don't know how the server checks that I am inactive, maybe for the server I was still active. I will keep an eye on that, in any case it is way better now, thank you.
